### ISSUE TITLE
More game support

### ISSUE THREAD

**Issue by Francois284Modz** [ZTzTopia/GTInternalAndroid#5]
is it possible to add support to work for other game then Growtopia

**Comment by ZTzTopia** [comment]
Yes, but you have to change all offsets in this source.

**Comment by Francois284Modz** [comment]
Sure the offset changing is nlt the problème is that it wont load for other game that i try it on

**Comment by KarmaMod** [comment]
it would be great if there is a way to use Imgui universally without hooking

**Comment by ozMod** [comment]
> it would be great if there is a way to use Imgui universally without hooking

You can do it with GLSurfaceView probably
